#!/bin/bash

# install-perl-modules
# Copyright (c) 2ndQuadrant 2010

# Install Perl modules for 2warm into the 2warm directory tree
# Does not require write access to the system Perl library

BASE=`pwd`
pushd TwoWarm-ConfigSetup
perl Makefile.PL INSTALL_BASE=$BASE/perl-lib
make
make install
popd
