#!/bin/bash

# archiveWALFile
# Copyright (c) 2ndQuadrant, 2009
#
# Intended for use as an archive_command
#
# $1 	WAL filepath to be archive e.g. ~/data/pg_xlog/00000001...
# $2	WAL filename to archive e.g. 00000001... 

#####################################################################
# Generic environment - shared by many of the scripts here.  Confirm
# environment is setup the way we expect before running anything
#####################################################################

function find_base
{
    # Validate if a hard-coded PGROOT points somewhere useful
    if [ ! -d "${PGROOT}" ] ; then
        # Figure out where this script is running from and guess
        # where PGROOT is at from there.  All of the major scripts
        # we run are 3 directory levels up from the PGROOT base.
        SCRIPTDIR=`dirname $0`
        pushd $SCRIPTDIR/../../..
        PGROOT=`pwd`
        popd
    fi

    # Basic validation that PGROOT has expected scripts
    CONFIGSCRIPT="${PGROOT}/2warm/global/replication/configSetup"
    if [ ! -f "${CONFIGSCRIPT}" ] ; then
      echo "ERROR:  PGROOT does not point to a complete 2warm installation."
      exit 1
    fi
}

# Bootstrap the rest of the standard initialization
find_base
source ${CONFIGSCRIPT}

#####################################################################
# End of generic environment setup
#####################################################################

require_other

# archive file
if [ -f "${LOCAL}/replication/archiving_active" ] ; then
    rsync -cz $1 ${OTHERNODE}:$ARCHIVE/$2
    if [ $? -ne 0 ] ; then
	  echo $0 " Standby rsync failed, rsyncing file to DRNODE instead"
	  rsync -cz $1/ ${DRNODE}:$ARCHIVE/$2
	  exit 1
    fi
fi

exit 0
