#!/bin/bash

# flushPrimary
# Copyright (c) 2ndQuadrant, 2009
#
# First part of a clean switchover from Primary to Standby
# Next step is to run triggerStandby on Standby node

#####################################################################
# Generic environment - shared by many of the scripts here.  Confirm
# environment is setup the way we expect before running anything
#####################################################################

function find_base
{
    # Validate if a hard-coded PGROOT points somewhere useful
    if [ ! -d "${PGROOT}" ] ; then
        # Figure out where this script is running from and guess
        # where PGROOT is at from there.  All of the major scripts
        # we run are 3 directory levels up from the PGROOT base.
        SCRIPTDIR=`dirname $0`
        pushd $SCRIPTDIR/../../.. >> /dev/null
        PGROOT=`pwd`
        popd >> /dev/null
    fi

    # Basic validation that PGROOT has expected scripts
    CONFIGSCRIPT="${PGROOT}/2warm/global/replication/configSetup"
    if [ ! -f "${CONFIGSCRIPT}" ] ; then
      echo "ERROR:  PGROOT does not point to a complete 2warm installation."
      exit 1
    fi
}

# Bootstrap the rest of the standard initialization
find_base
source ${CONFIGSCRIPT}

#####################################################################
# End of generic environment setup
#####################################################################

require_pgdata
primary_only
require_archive

# Save database log files, which might be copied over to the standby
# Not done in current implementation
#rsync -cav ${PGDATA}/pg_log/* ${ARCHIVE}

# Spawn off database script that does the flush
psql -f $GLOBAL/replication/archiverFlush &
PID=$!

# That starts with a 10 second sleep.  Wait one second to confirm it should
# have started, then prevent additional connections to the database through
# a smart shutdown.  The one we've already connected will survive this.
sleep 1
pg_ctl stop -m smart -w -t 5

# Wait for the script to finish
echo Waiting for archiver flush to complete:  approximately 30 seconds
wait $PID

# Completely stop the server
echo Stopping the server
pg_ctl stop -m immediate -w

# flush files to standby archive
rsync -cz $PGDATA/pg_xlog/* $OTHERNODE:$ARCHIVE/
exit_on_error "rsync to $OTHERNODE failed"

# flush files to DR archive
if [ -n "$DRNODE" ] ; then
  rsync -cz $PGDATA/pg_xlog/* $DRNODE:$ARCHIVE/
  exit_on_error "rsync to $DRNODE failed"
fi

exit 0
